spring.application.name=cinema-system-reservation

spring.datasource.url=jdbc:postgresql://localhost:5433/cinema_db
spring.datasource.username=cinema_user
spring.datasource.password=cinema_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true



