version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cinema_postgres
    restart: always
    environment:
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
      POSTGRES_DB: cinema_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: