spring.application.name=cinema-system-reservation

# ==============================================================
# Attention!
# This is the demo file. To run project with your own DB,
# create a file 'application-config.properties' and input your data.
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_db
spring.datasource.username=cinema_user
spring.datasource.password=cinema_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true



